using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SuperSimpleBlog.Models
{
    public class ApplicationDbContext : IdentityDbContext<IdentityUser>
    {
        public DbSet<Post> Posts { get; set; }
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
            Database.EnsureCreated();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // for the first run, uncomment the code below to initialize the DB with data 

            //modelBuilder.Entity<Post>().HasData(new Post[]
            //{
            //    new Post(){
            //        ID = "1",
            //        Title = "First post",
            //        Public = true,
            //        CoverImagePath = "", // leave this blank for now
            //        Excerpt = "Define the underlying",
            //        Content = "Define the underlying principles that drive decisions and strategy for your design language bleeding edge onward and upward"
            //        // The above text was generated by Office Ipsum http://officeipsum.com/index.php
            //    },
            //    new Post(){
            //        ID = "2",
            //        Title = "Second post",
            //        Public = true,
            //        CoverImagePath = "", // still blank
            //        Excerpt = "so what's our",
            //        Content = "so what's our go to market strategy?. Customer centric all hands on deck yet where the metal hits the meat define"
            //    },
            //    new Post(){
            //        ID = "3",
            //        Title = "Not visible",
            //        Public = false,
            //        CoverImagePath = "", // blank
            //        Excerpt = "not important",
            //        Content = "not important, you should not see this post"
            //    },
            //    new Post(){
            //        ID = "4",
            //        Title = "Third post",
            //        Public = true,
            //        CoverImagePath = "", // blank
            //        Excerpt = "the underlying",
            //        Content = "the underlying principles that drive decisions and strategy for your design language not the long pole",
            //        Deleted = true // this one should also not be visible
            //    },
            //    new Post(){
            //        ID = "5",
            //        Title = "Fourth post",
            //        Public = true,
            //        CoverImagePath = "", // blank
            //        Excerpt = "in the future",
            //        Content = "Post scheduling made super easy",
            //        Created = DateTime.Now.AddDays(3) // Post scheduling made easy
            //    },
            //    new Post(){
            //        ID = "6",
            //        Title = "Markdown Test",
            //        Public = true,
            //        CoverImagePath = "", // blank
            //        Excerpt = "Let's see what markdown can do",
            //        Content =   "# Hello world\n"+
            //                    "**Lorem** ipsum dolor sit"+
            //                    "amet, *consectetur* adipiscing elit. Sed"+
            //                    "eu est nec metus luctus tempus. Pellentesque"+
            //                    "at elementum sapien, ac faucibus sem"+
            //                    "![surprise](https://media.giphy.com/media/fdyZ3qI0GVZC0/giphy.gif)"
            //    },
            //    new Post(){
            //        ID = "7",
            //        Title = "Html Test",
            //        Public = true,
            //        CoverImagePath = "", // blank
            //        Excerpt = "Let's see what html can do",
            //        Content =   "<h2>It's a Title</h2><p>Hello!</p>"+
            //                    "<b>It's a b text!</b><br/>"+
            //                    "<hr/>"
            //    }
            //});            
        }
    }
}
